using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Sitiowebb.Data.Migrations
{
    public partial class FixVacationRequestIdIdentity2 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Forzar que la columna Id sea IDENTITY (autoincremental) en PostgreSQL
            migrationBuilder.Sql(@"
DO $$
BEGIN
    -- Si la columna Id NO tiene default (no es identity), la convertimos
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'VacationRequests'
          AND column_name = 'Id'
          AND column_default IS NULL
    ) THEN
        ALTER TABLE ""VacationRequests""
        ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END
$$;
");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // No intentamos deshacer el cambio (no es necesario para ti)
        }
    }
}